git clone https://github.com/matsyaos/appmotor
git clone https://github.com/matsyaos/qt-plugins
git clone https://github.com/matsyaos/gtk-themes
git clone https://github.com/matsyaos/screenlocker
git clone https://github.com/matsyaos/screenshot
git clone https://github.com/matsyaos/calculator
git clone https://github.com/matsyaos/kwin-plugins
git clone https://github.com/matsyaos/statusbar
git clone https://github.com/matsyaos/core
git clone https://github.com/matsyaos/launcher
git clone https://github.com/matsyaos/statusbar-test
git clone https://github.com/matsyaos/daemon
git clone https://github.com/matsyaos/libmatsya
git clone https://github.com/matsyaos/terminal
git clone https://github.com/matsyaos/debinstaller
git clone https://github.com/matsyaos/matsya-settings
git clone https://github.com/matsyaos/texteditor
git clone https://github.com/matsyaos/dock
git clone https://github.com/matsyaos/matsyaui
git clone https://github.com/matsyaos/videoplayer
git clone https://github.com/matsyaos/filemanager
git clone https://github.com/matsyaos/matsya-updater
git clone https://github.com/matsyaos/wallpappers
git clone https://github.com/matsyaos/icons
