gh repo clone matsyaos/appmotor
gh repo clone matsyaos/qt-plugins
gh repo clone matsyaos/gtk-themes
gh repo clone matsyaos/screenlocker
gh repo clone matsyaos/screenshot
gh repo clone matsyaos/calculator
gh repo clone matsyaos/kwin-plugins
gh repo clone matsyaos/statusbar
gh repo clone matsyaos/core
gh repo clone matsyaos/launcher
gh repo clone matsyaos/statusbar-test
gh repo clone matsyaos/daemon
gh repo clone matsyaos/libmatsya
gh repo clone matsyaos/terminal
gh repo clone matsyaos/debinstaller
gh repo clone matsyaos/matsya-settings
gh repo clone matsyaos/texteditor
gh repo clone matsyaos/dock
gh repo clone matsyaos/matsyaui
gh repo clone matsyaos/videoplayer
gh repo clone matsyaos/filemanager
gh repo clone matsyaos/matsya-updater
gh repo clone matsyaos/wallpappers
gh repo clone matsyaos/icons
